application:
  port: 3000
  
  websocket:
    host: '127.0.0.1'
    port: 7000
  
  eventmachine:
    host: '127.0.0.1'
    port: 5000
  
  connection:
    auth_key: "99-0-KK-9453-8322"
  
  rawdata:
      max_byte_size: 200